// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import ContactFormController from "./contact_form_controller";
import Carousel from '@stimulus-components/carousel'

application.register("hello", HelloController)
application.register('carousel', Carousel)
application.register('contact-form', ContactFormController)
