version: '3.2'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      # - redis
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    # environment:
    #   - RAILS_MASTER_KEY=55d35b31f33797cf38f77f5ffd672c68
      # - PGHOST=postgres
      # - PGUSER=postgres
      # - PGPASSWORD=password
      # - REDIS_URL=redis://redis:6379
      # - PORT=3000
    volumes:
      - .:/rails
      - "./node_modules:/rails/node_modules"
