ARG RUBY_VERSION=3.3.0
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim

ENV BINDING="0.0.0.0" \
    BUNDLE_PATH="/usr/local/bundle" \
    GEM_HOME="/usr/local/bundle"

RUN gem update --system && gem cleanup

ARG NODE_VERSION=20.11.0
ARG YARN_VERSION=1.22.21
ENV PATH=/usr/local/node/bin:$PATH

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl postgresql-client git libpq-dev libvips node-gyp pkg-config python-is-python3 && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt

RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    npm install -g yarn@$YARN_VERSION && \
    rm -rf /tmp/node-build-master

# Install packages needed to build gems and node modules

# Rails app lives here
WORKDIR /rails

COPY ./Gemfile* ./.ruby-version /rails/

RUN bundle install --jobs $(nproc) --retry 5

# COPY package.json yarn.lock /rails/
RUN yarn install

COPY . .

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]
# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD ["./bin/rails", "server"]